### PR TITLE
[feat] add compatibility with laravel 11

### PR DESCRIPTION
**Pull request by aryala7**
this pr adds Laravel 11 compatibility

### CODE REVIEW

**Comment by Sairahcaz** [comment]
@aryala7 thank you, this is awesome! I'll check the PR tomorrow.

**Comment by aryala7** [comment]
@Sairahcaz Ich freue mich sehr, dass du meine PR interessant findest. ✌🏻

**Comment by Sairahcaz** [comment]
Hi @aryala7, the tests are failing. The thing ist that doctrine/dbal has been removed from Laravel 11. So you can't just composer to make this work. Feel free to create a new PR which removes all doctrine dependencies from the package.

**Comment by aryala7** [comment]
@Sairahcaz ok i will open a new pull request

**Comment by mathieutu** [comment]
The issue in your PR is because of carbon missing for the test matrix.

However, some more work needs to be done for 11, as :
Screenshot 2024-04-17 at 23 43 16

**Comment by aryala7** [comment]
Yes I have already fixed the versioning section and going to create another pull request today

**Comment by mathieutu** [comment]
> create another pull request today
@aryala7 Did you take the time to work on it as planned?

**Pull request closed without merging**
