### PR TITLE
Fix error in PR #3 and refactoring

### PR DESCRIPTION
**Pull request by giagara**
I fixed the error in pr #3 and I've refactor it a little due to some duplicated code.

The error in #3 was about using `$field` and not `$column`
```php
// If column should be skipped
 if (in_array($field, $skip_columns)) {
    continue;
}
```

### CODE REVIEW

**Comment by Sairahcaz** [comment]
Can't merge it like this.
Did you saw, that the `constructor` in each implementation is a bit different?

Also if you wanna make sure a concrete function implementation exists just for instance do `abstract protected function getColumnsDefinitionsFromTable(): array;` in the parent class. This forces the concrete class to have such a function definition and if not, it throws these exception automatically...

And for the default `skip_columns`, why didn't you just set them in the config?
Maybe if somebody for some reason do not like this default, he could change it, but your approach hardcoded it...

Also please change **AbstractSchemaRulesResolver** in class names to **BaseSchemaRulesResolver**

I kinda like your approach, but it would be great if you could fix these things first!

**Comment by giagara** [comment]
You are fully correct. Sorry for my mistakes.
I'll work on it tomorrow.

Talking about `skip_columns` i though that those columns was always skipped but you are right, better not hardcode it and let the developer choose what to do, giving a default value.

**Comment by giagara** [comment]
I should have fixed all the issues

**Comment by Sairahcaz** [comment]
> I should have fixed all the issues

Your Base `generate` function global https://github.com/laracraft-tech/laravel-schema-rules/pull/4/files#diff-a236fcaba8fd777ce8b31ff7450c745c4073ee1f84444d8e10ad04358c6d11c2R20 will not work for the other drivers.

Please check them out, they have a slightly difference...

**Comment by Sairahcaz** [comment]
Okay I released it, thanks for you support!

https://github.com/laracraft-tech/laravel-schema-rules/releases/tag/v1.3.0

**Pull request merged**
